"""make document text one to one

Revision ID: 021e38dfb550
Revises: 2e863a50296d
Create Date: 2026-07-17 16:00:46.892224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '021e38dfb550'
down_revision: Union[str, Sequence[str], None] = '2e863a50296d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "uq_documents_text_id_doc",
        "documents_text",
        ["id_doc"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "uq_documents_text_id_doc",
        "documents_text",
        type_="unique",
    )
    # ### end Alembic commands ###
