"""add cascade delete document text

Revision ID: f922960a2687
Revises: 021e38dfb550
Create Date: 2026-07-17 16:18:47.271818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f922960a2687'
down_revision: Union[str, Sequence[str], None] = '021e38dfb550'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('documents_text_id_doc_fkey'), 'documents_text', type_='foreignkey')
    op.create_foreign_key(
        "documents_text_id_doc_fkey",
        "documents_text",
        "documents",
        ["id_doc"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "documents_text_id_doc_fkey",
        "documents_text",
        type_="foreignkey",
    )
    op.create_foreign_key(op.f('documents_text_id_doc_fkey'), 'documents_text', 'documents', ['id_doc'], ['id'])
    # ### end Alembic commands ###
