name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  lint:
    name: Ruff
    runs-on: ubuntu-latest

    steps:
      - name: Получить код
        uses: actions/checkout@v7

      - name: Установить Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"
          cache: pip
          cache-dependency-path: |
            requirements-api.txt
            requirements-dev.txt

      - name: Установить зависимости
        run: pip install -r requirements-dev.txt

      - name: Проверить код
        run: ruff check .

      - name: Проверить форматирование
        run: ruff format --check .

      - name: Запустить тесты
        run: python -m pytest -v